# Generated by Django 4.2.15 on 2026-03-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_user_display_name_email_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='search_tokens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
