'''
---------------------------------------------------
Project:        Braelo
Date:           Aug 14, 2024
Author:         Hamid
---------------------------------------------------

Description:
Django settings for Braelo project.

Generated by 'django-admin startproject' using Django 4.2.15.
---------------------------------------------------
'''

import os
import re
import base64
import binascii
import json
import logging
import urllib
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

try:
    from mongoengine import connect
except ImportError:
    connect = None  # type: ignore[misc, assignment]

_settings_log = logging.getLogger(__name__)
if connect is None:
    _settings_log.warning(
        "mongoengine is not installed; MongoEngine is disabled. "
        "Install: pip install mongoengine  (or pip install -r requirements.txt)"
    )

try:
    from firebase_admin import initialize_app, credentials  # type: ignore
except Exception:
    initialize_app = None
    credentials = None


# Load environment variables
try:
    load_dotenv()
    # Never log secret values (CI/deploy often has no .env)
    _settings_log.info(
        "OPENAI_API_KEY configured=%s",
        bool(os.getenv("OPENAI_API_KEY")),
    )
except ImportError:
    pass


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


def _env_csv(name: str, default: str = "") -> list:
    raw = os.getenv(name, default)
    return [x.strip() for x in (raw or "").split(",") if x.strip()]


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not str(raw).strip():
        return default
    try:
        return int(str(raw).strip(), 10)
    except ValueError:
        return default


# current_dir = os.getcwd()
# firebase_credentials = os.path.join(current_dir, 'config', 'credentials.json')

# # Initialize Firebase
# if not os.path.exists(firebase_credentials):
#     raise FileNotFoundError(
#         f"Firebase credentials file not found at: {firebase_credentials}"
#     )

# try:
#     cred = credentials.Certificate(firebase_credentials)
#     initialize_app(cred)
#     print("Firebase initialized successfully.")
# except Exception as e:
#     print(f"An error occurred while initializing Firebase: {e}")

# Get Base64 string from environment variable


_firebase_b64 = (
    os.getenv("FIREBASE_CREDENTIALS", "").strip()
    or os.getenv("FIREBASE_CREDENTIALS_BASE64", "").strip()
)
try:
    if _firebase_b64 and initialize_app and credentials:
        firebase_credentials_json = base64.b64decode(_firebase_b64).decode("utf-8")
        firebase_credentials = json.loads(firebase_credentials_json)
        cred = credentials.Certificate(firebase_credentials)
        initialize_app(cred)
        _settings_log.info("Firebase initialized successfully.")
    elif not _firebase_b64:
        _settings_log.warning(
            "Firebase initialization skipped: set FIREBASE_CREDENTIALS (Base64 JSON) in the environment."
        )
    else:
        _settings_log.warning("firebase_admin not installed; skipping Firebase init.")

except json.JSONDecodeError:
    _settings_log.warning("Firebase initialization skipped: invalid JSON credentials.")

except binascii.Error:
    _settings_log.warning("Firebase initialization skipped: invalid Base64 encoding.")

except Exception as e:
    _settings_log.warning("Firebase initialization skipped: %s", e)


GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "").strip()


# We need these lines below to allow the Google sign in popup to work.
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", default=True)

_allowed_default = (
    "localhost,127.0.0.1,169.254.129.4,169.254.129.2,"
    "braelo-v1-bdaqhdc4c7d9fdb7.canadacentral-01.azurewebsites.net,.azurewebsites.net"
)
ALLOWED_HOSTS = _env_csv("ALLOWED_HOSTS", _allowed_default)

# django-cors-headers 4.x prefers CORS_ALLOW_ALL_ORIGINS; it falls back to CORS_ORIGIN_ALLOW_ALL if unset
_cors_allow_all = _env_bool("CORS_ORIGIN_ALLOW_ALL", default=True)
CORS_ALLOW_ALL_ORIGINS = _env_bool(
    "CORS_ALLOW_ALL_ORIGINS", default=_cors_allow_all
)
CORS_ORIGIN_ALLOW_ALL = CORS_ALLOW_ALL_ORIGINS

# Default False in django-cors-headers: when True + CORS_ALLOW_ALL_ORIGINS, the middleware
# echoes the request Origin (instead of "*"), which fixes browsers / Axios when using
# Authorization or credentials with a cross-origin SPA.
CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", default=True)

# Optional explicit origins (comma-separated). If set, you usually want
# CORS_ALLOW_ALL_ORIGINS=False in the same environment.
_cors_explicit_origins = _env_csv("CORS_ALLOWED_ORIGINS", "")
if _cors_explicit_origins:
    CORS_ALLOWED_ORIGINS = _cors_explicit_origins

# When CORS_ALLOW_ALL_ORIGINS is False, these patterns still allow App Service + local dev.
CORS_ALLOWED_ORIGIN_REGEXES = [
    re.compile(r"^https://.+\.azurewebsites\.net$"),
    re.compile(r"^http://localhost(?::\d+)?$"),
    re.compile(r"^http://127\.0\.0\.1(?::\d+)?$"),
]

_csrf_default = (
    "https://braelo-v1-bdaqhdc4c7d9fdb7.canadacentral-01.azurewebsites.net,"
    "http://localhost,http://127.0.0.1,http://192.168.18.4"
)
CSRF_TRUSTED_ORIGINS = _env_csv("CSRF_TRUSTED_ORIGINS", _csrf_default)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Email backend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# for testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP server settings
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "noreply@example.com",
)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'chats',
    'listings',
    'notifications',
    'fcm_django',
    "admin_panel",
    "chatbot",
]

AUTH_USER_MODEL = 'users.User'

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'PAGE_SIZE': 15,
}

# Set up JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'BLACKLIST_AFTER_ROTATION': _env_bool('JWT_BLACKLIST_AFTER_ROTATION', default=True),
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=_env_int('JWT_ACCESS_TOKEN_MINUTES', 2880)
    ),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(
        days=_env_int('JWT_SLIDING_REFRESH_DAYS', 7)
    ),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=_env_int('JWT_SLIDING_TOKEN_DAYS', 30)),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(
        days=_env_int('JWT_SLIDING_REFRESH_LATE_DAYS', 1)
    ),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(
        days=_env_int('JWT_SLIDING_TOKEN_LATE_DAYS', 30)
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'applications.custom_authentication.middleware.JWTAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0").strip()
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_URL)],  # Replace with your Redis host and port
        },
    },
}

# Azure Blob Storage (listings, chat media, business images)
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "").strip()
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY", "").strip()
AZURE_CONTAINER_NAME = os.getenv("AZURE_CONTAINER_NAME", "braelo").strip()
AZURE_CUSTOM_DOMAIN = os.getenv("AZURE_CUSTOM_DOMAIN", "").strip()
AZURE_STORAGE_CONNECTION_STRING = os.getenv(
    "AZURE_STORAGE_CONNECTION_STRING", ""
).strip()
if not AZURE_STORAGE_CONNECTION_STRING and AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY:
    AZURE_STORAGE_CONNECTION_STRING = (
        "DefaultEndpointsProtocol=https;"
        f"AccountName={AZURE_ACCOUNT_NAME};"
        f"AccountKey={AZURE_ACCOUNT_KEY};"
        "EndpointSuffix=core.windows.net"
    )
if not AZURE_CUSTOM_DOMAIN and AZURE_ACCOUNT_NAME and AZURE_CONTAINER_NAME:
    AZURE_CUSTOM_DOMAIN = (
        f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER_NAME}"
    )

# Twilio
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "").strip()
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "").strip()
TWILIO_VERIFY_SERVICE_SID = os.getenv("TWILIO_VERIFY_SERVICE_SID", "").strip()

# Firebase Cloud Messaging (push)
FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": os.getenv("FCM_SERVER_KEY", "").strip(),
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # relative to your repo
    }
}

# ---------------------------------------------------------------------------
# MongoDB (mongoengine + chatbot pymongo share these env vars)
# ---------------------------------------------------------------------------
MONGO_DB_NAME = (os.getenv("MONGO_DB_NAME", "braelo") or "braelo").strip()


def _resolve_mongo_uri() -> str:
    for key in (
        "MONGO_URI",
        "CUSTOMCONNSTR_MONGO_URI",
        "CUSTOMCONNSTR_mongodb",
        "MONGODB_URI",
        "MONGO_URL",
    ):
        v = os.getenv(key, "").strip()
        if v:
            return v
    return ""


def _normalize_mongo_uri_credentials(uri: str) -> str:
    """Encode userinfo in mongodb:// URIs so PyMongo 4+ accepts special characters."""
    uri = (uri or "").strip()
    if not uri or "://" not in uri:
        return uri
    try:
        scheme, rest = uri.split("://", 1)
        if scheme not in ("mongodb", "mongodb+srv"):
            return uri
        if "@" not in rest:
            return uri
        authority, hostpath = rest.split("@", 1)
        if ":" not in authority:
            return uri
        colon = authority.index(":")
        user_part = authority[:colon]
        pass_part = authority[colon + 1 :]
        if not user_part:
            return uri
        user_raw = urllib.parse.unquote(user_part)
        pass_raw = urllib.parse.unquote(pass_part)
        user_enc = urllib.parse.quote_plus(user_raw, safe="")
        pass_enc = urllib.parse.quote_plus(pass_raw, safe="")
        return f"{scheme}://{user_enc}:{pass_enc}@{hostpath}"
    except Exception:
        return uri


MONGO_URI = _resolve_mongo_uri()
_mongo_username = os.getenv("MONGO_USERNAME", "").strip()
_mongo_password_raw = os.getenv("MONGO_PASSWORD", "").strip()
DJANGO_SKIP_MONGOENGINE = os.getenv("DJANGO_SKIP_MONGOENGINE", "").lower() in (
    "1",
    "true",
    "yes",
)

# Build Atlas URI only when username+password + host are set (avoid mongodb+srv://:@...)
_mongo_atlas_host = os.getenv("MONGO_ATLAS_HOST", "").strip()
if not MONGO_URI and _mongo_username and _mongo_password_raw and _mongo_atlas_host:
    # Allow env vars to be either raw or already URL-encoded.
    _enc_user = urllib.parse.quote_plus(urllib.parse.unquote(_mongo_username), safe="")
    _enc_pw = urllib.parse.quote_plus(urllib.parse.unquote(_mongo_password_raw), safe="")
    MONGO_URI = (
        f"mongodb+srv://{_enc_user}:{_enc_pw}"
        f"@{_mongo_atlas_host}/{MONGO_DB_NAME}?retryWrites=true&w=majority"
    )

if MONGO_URI:
    MONGO_URI = _normalize_mongo_uri_credentials(MONGO_URI)


def _mongo_uri_valid(uri: str) -> bool:
    if not uri or not uri.strip():
        return False
    u = uri.strip()
    if u.startswith(("mongodb://localhost", "mongodb://127.0.0.1")):
        return True
    if "://" not in u or "@" not in u:
        return False
    try:
        _, rest = u.split("://", 1)
        userinfo, _, _ = rest.partition("@")
    except (ValueError, IndexError):
        return False
    userinfo = userinfo.strip()
    if not userinfo or userinfo.startswith(":"):
        return False
    return True


# GitHub Actions / other CI often has no Mongo secrets — don't crash manage.py
_auto_skip_mongo_ci = (
    os.getenv("CI", "").lower() in ("true", "1", "yes")
    or os.getenv("GITHUB_ACTIONS", "").lower() == "true"
) and not _mongo_uri_valid(MONGO_URI)


if connect is None:
    pass  # already logged at import time
elif DJANGO_SKIP_MONGOENGINE or _auto_skip_mongo_ci:
    _settings_log.warning(
        "MongoEngine not initialized (%s). Set MONGO_URI or DJANGO_SKIP_MONGOENGINE=false with valid credentials.",
        "DJANGO_SKIP_MONGOENGINE"
        if DJANGO_SKIP_MONGOENGINE
        else "CI without MONGO_URI",
    )
elif _mongo_uri_valid(MONGO_URI):
    try:
        connect(
            alias="default",
            db=MONGO_DB_NAME,
            host=MONGO_URI,
            authentication_source="admin",
        )
        _settings_log.info("MongoEngine default connection registered (db=%s)", MONGO_DB_NAME)
    except Exception as exc:
        _settings_log.exception("MongoEngine connect failed: %s", exc)
        raise ImproperlyConfigured(
            "Could not connect MongoEngine to MongoDB. Check MONGO_URI / Atlas network access. "
            f"Original error: {exc}"
        ) from exc
elif DEBUG:
    try:
        connect(
            alias="default",
            db=MONGO_DB_NAME,
            host="mongodb://127.0.0.1:27017",
            authentication_source="admin",
        )
        _settings_log.warning(
            "MONGO_URI missing/invalid; MongoEngine using DEBUG fallback mongodb://127.0.0.1:27017"
        )
    except Exception as exc:
        _settings_log.warning(
            "MongoEngine DEBUG localhost connect failed (%s). Use MONGO_URI or set DJANGO_SKIP_MONGOENGINE=1 in CI.",
            exc,
        )
else:
    raise ImproperlyConfigured(
        "MongoDB is required but MONGO_URI is missing or invalid. "
        "Set MONGO_URI (or MONGO_USERNAME + MONGO_PASSWORD) and MONGO_DB_NAME."
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Chatbot app (RAG, business matching, OpenAI). Uses same .env as Braelo.
# ---------------------------------------------------------------------------
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
# Business directory: MongoDB vs Django Business table. If USE_MONGO is unset but MONGO_URI is
# valid (typical local/deploy .env), default to True so local matches production without a second flag.
_use_mongo_env = os.getenv("USE_MONGO", "").strip().lower()
if _use_mongo_env in ("false", "0", "no", "off"):
    USE_MONGO = False
elif _use_mongo_env in ("true", "1", "yes", "on"):
    USE_MONGO = True
else:
    USE_MONGO = bool(_mongo_uri_valid(MONGO_URI))
# MONGO_URI / MONGO_DB_NAME are defined above (shared with mongoengine)

GPT_MODEL = os.getenv('GPT_MODEL', 'gpt-4o-mini')
# Google Places (Nearby / Text / Details) — server-side only; set in .env (not VITE_).
GOOGLE_PLACES_API_KEY = os.getenv('GOOGLE_PLACES_API_KEY', '')
GOOGLE_PLACES_RADIUS_M = int(os.getenv('GOOGLE_PLACES_RADIUS_M', '6000'))
GOOGLE_PLACES_MAX_RESULTS = int(os.getenv('GOOGLE_PLACES_MAX_RESULTS', '7'))
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')
KNOWLEDGE_SIMILARITY_THRESHOLD = float(os.getenv('KNOWLEDGE_SIMILARITY_THRESHOLD', '0.55'))
RAG_TOP_K = int(os.getenv('RAG_TOP_K', '8'))
# Hybrid retrieval: cosine on embeddings + lexical overlap on precomputed KB tokens.
# RAG_SIMILARITY_THRESHOLD / FALLBACK apply to the combined hybrid score (not raw cosine).
RAG_HYBRID_EMBEDDING_WEIGHT = float(os.getenv('RAG_HYBRID_EMBEDDING_WEIGHT', '0.58'))
RAG_SIMILARITY_THRESHOLD = float(os.getenv('RAG_SIMILARITY_THRESHOLD', '0.32'))
RAG_SIMILARITY_FALLBACK = float(os.getenv('RAG_SIMILARITY_FALLBACK', '0.20'))
# LLM paraphrase → Portuguese-ish search line to align with PT-heavy KB (retrieval only; no new facts).
RAG_QUERY_REWRITE = os.getenv('RAG_QUERY_REWRITE', 'true').lower() in ('true', '1', 'yes')
# Strong match → short-circuit to KB-style answer. (Second “min confident” gate in chat_flow was removed:
# hybrid scores often land ~0.35–0.45 for good matches; retrieval thresholds below are enough.)
RAG_STRONG_MATCH_HYBRID = float(os.getenv('RAG_STRONG_MATCH_HYBRID', '0.68'))
RAG_MIN_CONFIDENT_HYBRID = float(os.getenv('RAG_MIN_CONFIDENT_HYBRID', '0.46'))  # unused; kept for .env compatibility
# Raw cosine floor (optional second gate): hybrid can be boosted by lex; keep cosine from garbage-matching.
RAG_EMBEDDING_MIN_FOR_MATCH = float(os.getenv('RAG_EMBEDDING_MIN_FOR_MATCH', '0.18'))
# DOCX knowledge base: set DOCX_DATA_DIR in .env to your folder (can be outside braelo). Default: parent folder / documents
DOCX_DATA_DIR = Path(os.getenv('DOCX_DATA_DIR', str(BASE_DIR.parent / 'documents')))
MAX_BUSINESS_RESULTS = int(os.getenv('MAX_BUSINESS_RESULTS', '20'))
BUSINESS_RADIUS_MILES = float(os.getenv('BUSINESS_RADIUS_MILES', '25'))
BUSINESS_RADIUS_FALLBACK_MILES = float(os.getenv('BUSINESS_RADIUS_FALLBACK_MILES', '50'))
MIN_BUSINESS_RESULTS = int(os.getenv('MIN_BUSINESS_RESULTS', '3'))
# Comma-separated Mongo collection names. Default is Lista/flat `businesses` only (import_lista_business_mongo).
# Legacy `business_listings` is opt-in, e.g. MONGO_BUSINESS_COLLECTIONS=business_listings,businesses
MONGO_BUSINESS_COLLECTIONS = [
    x.strip() for x in os.getenv('MONGO_BUSINESS_COLLECTIONS', 'businesses').split(',') if x.strip()
]
# After a KB match, surface local providers when intent has category/subcategory + user location
KB_PROVIDER_SUGGESTIONS = os.getenv('KB_PROVIDER_SUGGESTIONS', 'true').lower() in ('true', '1', 'yes')
KB_PROVIDER_SUGGESTIONS_MAX = int(os.getenv('KB_PROVIDER_SUGGESTIONS_MAX', '3'))
# Verbose [SessionGeo] logs in chat_flow (terminal). Set false in production to reduce noise.
BRAELO_SESSION_GEO_DEBUG = os.getenv("BRAELO_SESSION_GEO_DEBUG", "true").lower() in (
    "1",
    "true",
    "yes",
)
# Verbose [BraeloAgent:…] logs for the agent wrapper layer (Tier 2a0 + learning).
BRAELO_AGENT_DEBUG = os.getenv("BRAELO_AGENT_DEBUG", "true").lower() in (
    "1",
    "true",
    "yes",
)
# Persist learning_logs to Mongo when URI/DB available; disable to log to stdout only.
BRAELO_LEARNING_LOG_TO_MONGO = os.getenv("BRAELO_LEARNING_LOG_TO_MONGO", "true").lower() in (
    "1",
    "true",
    "yes",
)
SUPPORTED_LANGUAGES = ['en', 'es', 'pt']
LANGUAGE_NAMES = {'en': 'English', 'es': 'Spanish', 'pt': 'Portuguese'}
BRAELO_MONGO_URI = os.getenv('BRAELO_MONGO_URI', os.getenv('BRAELO_MONGO_DB_URI', ''))  # optional: for sync_braelo_mongo
