'''
---------------------------------------------------
Project:        Braelo
Date:           Aug 14, 2024
Author:         Hamid
---------------------------------------------------

Description:
Django settings for Braelo project.

Generated by 'django-admin startproject' using Django 4.2.15.
---------------------------------------------------
'''

import os
import base64
import binascii
import json
import logging
import urllib
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from mongoengine import connect

_settings_log = logging.getLogger(__name__)

try:
    from firebase_admin import initialize_app, credentials  # type: ignore
except Exception:
    initialize_app = None
    credentials = None


# Load environment variables
try:
    load_dotenv()
    # Never log secret values (CI/deploy often has no .env)
    _settings_log.info(
        "OPENAI_API_KEY configured=%s",
        bool(os.getenv("OPENAI_API_KEY")),
    )
except ImportError:
    pass

# current_dir = os.getcwd()
# firebase_credentials = os.path.join(current_dir, 'config', 'credentials.json')

# # Initialize Firebase
# if not os.path.exists(firebase_credentials):
#     raise FileNotFoundError(
#         f"Firebase credentials file not found at: {firebase_credentials}"
#     )

# try:
#     cred = credentials.Certificate(firebase_credentials)
#     initialize_app(cred)
#     print("Firebase initialized successfully.")
# except Exception as e:
#     print(f"An error occurred while initializing Firebase: {e}")

# Get Base64 string from environment variable


try:
    encoded_json="ew0KICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAicHJvamVjdF9pZCI6ICJicmFlbG8tN2E5M2YiLA0KICAicHJpdmF0ZV9rZXlfaWQiOiAiYjY4OGM4MWE4NWI3MjM5YTg2MzA1MmE1MTQ5MTJiOTZlYWFlOGFjNyIsDQogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ2ZORm12aVc3aFFna2xcbmR1R2xwYmhIeFpIODArOERsU0JGSkw0L25rNG1DelF1Y21PNzMxSUtabFY0dXYxM2RuNzNkYk5GR2VLNVRiaTNcbnZKT2d5QTNSZ0plV3hiL2pnTUJEanRsR2RLcVdpbWtyOE4zVUM4M0QzMjVqTnJHWVFtRnJRNnE2THd6aXdEZ1NcbjU5S2ROOWt5WCtqS0hpbHZqeFJGMTlLV3BxdjgzMEZiMVhiZ1g5WXd4MnhsQlB4eWo1aDJFZHBNSHhCMCs5L0pcbldMV2dXKzArK0tFemU3bkI0eG9VaHBWWWhQM2hnaU5CVThzdnVCRHczSTZwbTBGNnNkaFgzL2hkWTEyL0RFRGxcbmRTdC9pR0I4U21BS1N4alNwREI4US9DbkhML1RZV2NXa0QweXZwNmZZcjNuekQ2cW4rWUpBWHRwYnhwSVpQNXlcbmJNekoyTkM3QWdNQkFBRUNnZ0VBQTVFOE96czBvVmFGOXZGeGYvRTFMbUtHY1doY1VETzh1OS9sWlc2S0tMOFNcbmhjSHBhekhIV0ZWUHIvdGNwNXNmb0RMaWQvZHJCYVR3c1NsSUU0KzRBNHhDbVUzSURYUjZtbWp1aEc0anptaStcbmo0My9vbnM3T3ByY2tkdU5ZakNHbDAwMlc2S25Rc04wM2pPVW5CSSt5eXFzQUM5cDFVYWErUytyVjlYWFA3ekZcbjNBc0V0b1lsazFlVExMTlFwS0QyVXg2VE1kZ0ZhTnhqVndaUDdJbDZ3N25nTlBwQnZxWk1qRHJXRHAyOEJRd1FcbngvaTNjRVhGOU84Q1NPWW5XV2YwQmExUDJiZ0ExRENGZWx4SElNK3JvQm15ZjBlb1FhdHVOVUdGdzJEYTNpVDlcbmE5RkpmV1BWU094ckFtZDNDQkNMZHNJTEtmMk9hcHAzcnBzT2p0L1Y3UUtCZ1FDOGRyKzdLdEtWZ1hDTmFyQlJcbnNLcjl2NGFnTitNa1dEK2FCMUVEWG1yREdPbnk3NnJKYmJ3b3BUeklOZ2FLM2w3WVl5U2N6cWZEbmZyM0NDU1VcblJSL2xKMWc1U0UxdjkzaEg5bS9yeHNsblFxR1YvdUJnMWZyWTZGL3piSExHSXJZeE0vQmZEMVV0eGZhVjZMSDVcbllUZ00zcUU0OWROckI2OGc2QlFvQmdMZzFRS0JnUURZUVdtZ21BY1hIQmZ2bEFDVXpVc0hwMDdFZ2w4WG9LWkZcbnI1eXJESjFaQWNYU3orVUk3TnI5TW1HTUNCNmg4Y2NFRlo3dzErc0xDeEJ5eHNmSVpOanA3WEZ0ZmVITDdTdjBcbjhkb3hKbGlSTVErZ0gzQUhncS9RUkZ0bWMvOUVDbmpuMGZDZGJwUHlQaVlBUitPTEF6bTcwMktnYUgvN2xKVUtcbnhBSE15UDh6VHdLQmdRQ2pyQzJQQ3YyZndhNVI0cG9HRi93b0t6RnI2NTFrYncrdFlUVkdTN1ZFZ2xxTEZRR3BcbnRaZDNaU21JWndML2oyZW5YVkxxcTc2ZThKQ0lBWlppL2pWWStmWndxUTQzY3lBT3YwTXI3SlAxRGJUdlkwN1NcblNvTno1VHVQV0Z2RkgxaERHdXhpWWhxRGlpMUF1N24wN2kyVFg3VjhsbUZwemw2Vm9YZi8ybGlka1FLQmdRQzRcblQ0Zm5CNnVEVnI1UHdxUjhMancwV2JRWVo4VUVMamVJVFJRSjlNWm1oY3hFMEVzMFFDcWtnYndCelNuT2ZISlNcbldOc09DZmlaZ09TVDdqZDM0L3U3NUZNNExvR3pmSUJxVTNiVFRRdFBNN0ZObDMyejZQNVBVdk5UYnFteEkvdklcbkdIWXF0NFFBZ2xlQkJjUTVScForTHJ0d1c2QTRtM29yb3NLbDl1a0tvUUtCZ0E0eEt3dWZnbWs1clpjVGoyL21cbmRmNXdoK0IyMVRFdjFTNU41SitWQ3BJQkg0Qm5UMVFPcDhRMmZIRFdMVk9JUXlsVU9WUnBua2pSN3ZCdGIrOGlcbjlSQVUvdUdQd3lVYS9uUldQVXNWakFWMGp3VFdNdnJQRDhqa3hkbXFtWnR2azY3M3grWkNLTklsR282RTN1UGRcbnZVOWp4N3dXTWdmR1o2cVkwMk5KNlYvL1xuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwNCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1kcTBvZkBicmFlbG8tN2E5M2YuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAiY2xpZW50X2lkIjogIjEwMDA5NjgzMTE5MDI2MjI3OTE0MCIsDQogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsDQogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLA0KICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsDQogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWRxMG9mJTQwYnJhZWxvLTdhOTNmLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwNCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSINCn0NCg=="

    # 🔓 Decode Base64 string
    firebase_credentials_json = base64.b64decode(encoded_json).decode("utf-8")
    firebase_credentials = json.loads(firebase_credentials_json)

    # 🔥 Initialize Firebase
    if initialize_app and credentials:
        cred = credentials.Certificate(firebase_credentials)
        initialize_app(cred)
        _settings_log.info("Firebase initialized successfully.")
    else:
        _settings_log.warning("firebase_admin not installed; skipping Firebase init.")

except json.JSONDecodeError:
    _settings_log.warning("Firebase initialization skipped: invalid JSON credentials.")

except binascii.Error:
    _settings_log.warning("Firebase initialization skipped: invalid Base64 encoding.")

except Exception as e:
    _settings_log.warning("Firebase initialization skipped: %s", e)


GOOGLE_OAUTH_CLIENT_ID = (
    "221272028067-cnm21hi90qmfp0jggj62148fetbv8qbn.apps.googleusercontent.com"
)


# We need these lines below to allow the Google sign in popup to work.
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    'django-insecure-d(rn*9qo8w(8^+06+f481^h-ncd8^5*2b%&f0dp&_yc4bgsdo8'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '169.254.129.4',
    '169.254.129.2',
    'braelo-v1-bdaqhdc4c7d9fdb7.canadacentral-01.azurewebsites.net',
    '.azurewebsites.net',
]
CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [
    'https://braelo-v1-bdaqhdc4c7d9fdb7.canadacentral-01.azurewebsites.net',
    'http://localhost',
    'http://127.0.0.1',
    'http://192.168.18.4',
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Email backend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# for testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SMTP server settings
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server (adjust for other providers)
EMAIL_PORT = 587  # Typically 587 for TLS
EMAIL_USE_TLS = True  # Use TLS (Transport Layer Security) for security

# Your email address and password
EMAIL_HOST_USER = 'braelo.fl@gmail.com'
EMAIL_HOST_PASSWORD = 'kgpv txaa anwb bvke'
DEFAULT_FROM_EMAIL = 'braelo.fl@gmail.com'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'users',
    'chats',
    'listings',
    'notifications',
    'fcm_django',
    "admin_panel",
    "chatbot",
]

AUTH_USER_MODEL = 'users.User'

# JWT settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'PAGE_SIZE': 15,
}

# Set up JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=2880),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'applications.custom_authentication.middleware.JWTAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REDIS_URL = os.getenv(
    "REDIS_URL",
    "redis://:Ds5XpZYB6BUKreYFgRdrFKXYG4UGsojS@redis-15589.c53.west-us.azure.redns.redis-cloud.com:15589/0",
)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_URL)],  # Replace with your Redis host and port
        },
    },
}

# S3 configurations
AZURE_ACCOUNT_NAME = 'braelos3'
AZURE_ACCOUNT_KEY = '5PkRWE5PK49PotcquKuVgZ6jLN261i8VNuqqdpTKJJekYcr2EWwrrlRyqV/s7a+mLOrV/YKBZDOX+AStNDj6pQ=='
AZURE_CONTAINER_NAME = 'braelo'
AZURE_CUSTOM_DOMAIN = 'https://braelos3.blob.core.windows.net/braelo'

# Twilio Setting
TWILIO_ACCOUNT_SID = 'ACd73fc3ad8cee9529a484342740e6161b'
TWILIO_AUTH_TOKEN = 'ef5f648b70cf84215b51e54d44037013 '
TWILIO_VERIFY_SERVICE_SID = 'VAcd6f5d07809c6f1e0d61f76bb64ce123'

# Firebase notifications
FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "your-fcm-server-key-here",
}


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # relative to your repo
    }
}

# ---------------------------------------------------------------------------
# MongoDB (mongoengine + chatbot pymongo share these env vars)
# ---------------------------------------------------------------------------
MONGO_DB_NAME = (os.getenv("MONGO_DB_NAME", "braelo") or "braelo").strip()


def _resolve_mongo_uri() -> str:
    for key in (
        "MONGO_URI",
        "CUSTOMCONNSTR_MONGO_URI",
        "CUSTOMCONNSTR_mongodb",
        "MONGODB_URI",
        "MONGO_URL",
    ):
        v = os.getenv(key, "").strip()
        if v:
            return v
    return ""


def _normalize_mongo_uri_credentials(uri: str) -> str:
    """Encode userinfo in mongodb:// URIs so PyMongo 4+ accepts special characters."""
    uri = (uri or "").strip()
    if not uri or "://" not in uri:
        return uri
    try:
        scheme, rest = uri.split("://", 1)
        if scheme not in ("mongodb", "mongodb+srv"):
            return uri
        if "@" not in rest:
            return uri
        authority, hostpath = rest.split("@", 1)
        if ":" not in authority:
            return uri
        colon = authority.index(":")
        user_part = authority[:colon]
        pass_part = authority[colon + 1 :]
        if not user_part:
            return uri
        user_raw = urllib.parse.unquote(user_part)
        pass_raw = urllib.parse.unquote(pass_part)
        user_enc = urllib.parse.quote_plus(user_raw, safe="")
        pass_enc = urllib.parse.quote_plus(pass_raw, safe="")
        return f"{scheme}://{user_enc}:{pass_enc}@{hostpath}"
    except Exception:
        return uri


MONGO_URI = _resolve_mongo_uri()
_mongo_username = os.getenv("MONGO_USERNAME", "").strip()
_mongo_password_raw = os.getenv("MONGO_PASSWORD", "").strip()
DJANGO_SKIP_MONGOENGINE = os.getenv("DJANGO_SKIP_MONGOENGINE", "").lower() in (
    "1",
    "true",
    "yes",
)

# Build Atlas URI only when username+password are set (avoid mongodb+srv://:@...)
if not MONGO_URI and _mongo_username and _mongo_password_raw:
    # Allow env vars to be either raw or already URL-encoded.
    _enc_user = urllib.parse.quote_plus(urllib.parse.unquote(_mongo_username), safe="")
    _enc_pw = urllib.parse.quote_plus(urllib.parse.unquote(_mongo_password_raw), safe="")
    MONGO_URI = (
        f"mongodb+srv://{_enc_user}:{_enc_pw}"
        f"@cluster0.7j4rnkk.mongodb.net/{MONGO_DB_NAME}?retryWrites=true&w=majority"
    )

if MONGO_URI:
    MONGO_URI = _normalize_mongo_uri_credentials(MONGO_URI)


def _mongo_uri_valid(uri: str) -> bool:
    if not uri or not uri.strip():
        return False
    u = uri.strip()
    if u.startswith(("mongodb://localhost", "mongodb://127.0.0.1")):
        return True
    if "://" not in u or "@" not in u:
        return False
    try:
        _, rest = u.split("://", 1)
        userinfo, _, _ = rest.partition("@")
    except (ValueError, IndexError):
        return False
    userinfo = userinfo.strip()
    if not userinfo or userinfo.startswith(":"):
        return False
    return True


# GitHub Actions / other CI often has no Mongo secrets — don't crash manage.py
_auto_skip_mongo_ci = (
    os.getenv("CI", "").lower() in ("true", "1", "yes")
    or os.getenv("GITHUB_ACTIONS", "").lower() == "true"
) and not _mongo_uri_valid(MONGO_URI)


if DJANGO_SKIP_MONGOENGINE or _auto_skip_mongo_ci:
    _settings_log.warning(
        "MongoEngine not initialized (%s). Set MONGO_URI or DJANGO_SKIP_MONGOENGINE=false with valid credentials.",
        "DJANGO_SKIP_MONGOENGINE"
        if DJANGO_SKIP_MONGOENGINE
        else "CI without MONGO_URI",
    )
elif _mongo_uri_valid(MONGO_URI):
    try:
        connect(
            alias="default",
            db=MONGO_DB_NAME,
            host=MONGO_URI,
            authentication_source="admin",
        )
        _settings_log.info("MongoEngine default connection registered (db=%s)", MONGO_DB_NAME)
    except Exception as exc:
        _settings_log.exception("MongoEngine connect failed: %s", exc)
        raise ImproperlyConfigured(
            "Could not connect MongoEngine to MongoDB. Check MONGO_URI / Atlas network access. "
            f"Original error: {exc}"
        ) from exc
elif DEBUG:
    try:
        connect(
            alias="default",
            db=MONGO_DB_NAME,
            host="mongodb://127.0.0.1:27017",
            authentication_source="admin",
        )
        _settings_log.warning(
            "MONGO_URI missing/invalid; MongoEngine using DEBUG fallback mongodb://127.0.0.1:27017"
        )
    except Exception as exc:
        _settings_log.warning(
            "MongoEngine DEBUG localhost connect failed (%s). Use MONGO_URI or set DJANGO_SKIP_MONGOENGINE=1 in CI.",
            exc,
        )
else:
    raise ImproperlyConfigured(
        "MongoDB is required but MONGO_URI is missing or invalid. "
        "Set MONGO_URI (or MONGO_USERNAME + MONGO_PASSWORD) and MONGO_DB_NAME."
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Chatbot app (RAG, business matching, OpenAI). Uses same .env as Braelo.
# ---------------------------------------------------------------------------
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
USE_MONGO = os.getenv('USE_MONGO', 'false').lower() in ('true', '1', 'yes')
# MONGO_URI / MONGO_DB_NAME are defined above (shared with mongoengine)

GPT_MODEL = os.getenv('GPT_MODEL', 'gpt-4o-mini')
# Google Places (Nearby / Text / Details) — server-side only; set in .env (not VITE_).
GOOGLE_PLACES_API_KEY = os.getenv('GOOGLE_PLACES_API_KEY', '')
GOOGLE_PLACES_RADIUS_M = int(os.getenv('GOOGLE_PLACES_RADIUS_M', '6000'))
GOOGLE_PLACES_MAX_RESULTS = int(os.getenv('GOOGLE_PLACES_MAX_RESULTS', '7'))
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')
KNOWLEDGE_SIMILARITY_THRESHOLD = float(os.getenv('KNOWLEDGE_SIMILARITY_THRESHOLD', '0.55'))
RAG_TOP_K = int(os.getenv('RAG_TOP_K', '8'))
# Hybrid retrieval: cosine on embeddings + lexical overlap on precomputed KB tokens.
# RAG_SIMILARITY_THRESHOLD / FALLBACK apply to the combined hybrid score (not raw cosine).
RAG_HYBRID_EMBEDDING_WEIGHT = float(os.getenv('RAG_HYBRID_EMBEDDING_WEIGHT', '0.58'))
RAG_SIMILARITY_THRESHOLD = float(os.getenv('RAG_SIMILARITY_THRESHOLD', '0.32'))
RAG_SIMILARITY_FALLBACK = float(os.getenv('RAG_SIMILARITY_FALLBACK', '0.20'))
# LLM paraphrase → Portuguese-ish search line to align with PT-heavy KB (retrieval only; no new facts).
RAG_QUERY_REWRITE = os.getenv('RAG_QUERY_REWRITE', 'true').lower() in ('true', '1', 'yes')
# Strong match → short-circuit to KB-style answer. (Second “min confident” gate in chat_flow was removed:
# hybrid scores often land ~0.35–0.45 for good matches; retrieval thresholds below are enough.)
RAG_STRONG_MATCH_HYBRID = float(os.getenv('RAG_STRONG_MATCH_HYBRID', '0.68'))
RAG_MIN_CONFIDENT_HYBRID = float(os.getenv('RAG_MIN_CONFIDENT_HYBRID', '0.46'))  # unused; kept for .env compatibility
# Raw cosine floor (optional second gate): hybrid can be boosted by lex; keep cosine from garbage-matching.
RAG_EMBEDDING_MIN_FOR_MATCH = float(os.getenv('RAG_EMBEDDING_MIN_FOR_MATCH', '0.18'))
# DOCX knowledge base: set DOCX_DATA_DIR in .env to your folder (can be outside braelo). Default: parent folder / documents
DOCX_DATA_DIR = Path(os.getenv('DOCX_DATA_DIR', str(BASE_DIR.parent / 'documents')))
MAX_BUSINESS_RESULTS = int(os.getenv('MAX_BUSINESS_RESULTS', '5'))
BUSINESS_RADIUS_MILES = float(os.getenv('BUSINESS_RADIUS_MILES', '25'))
BUSINESS_RADIUS_FALLBACK_MILES = float(os.getenv('BUSINESS_RADIUS_FALLBACK_MILES', '50'))
MIN_BUSINESS_RESULTS = int(os.getenv('MIN_BUSINESS_RESULTS', '3'))
# Comma-separated Mongo collection names: legacy business_listings + flat `businesses` docs (name/category/lat/lon/contact_info)
MONGO_BUSINESS_COLLECTIONS = [
    x.strip() for x in os.getenv('MONGO_BUSINESS_COLLECTIONS', 'business_listings,businesses').split(',') if x.strip()
]
# After a KB match, surface local providers when intent has category/subcategory + user location
KB_PROVIDER_SUGGESTIONS = os.getenv('KB_PROVIDER_SUGGESTIONS', 'true').lower() in ('true', '1', 'yes')
KB_PROVIDER_SUGGESTIONS_MAX = int(os.getenv('KB_PROVIDER_SUGGESTIONS_MAX', '3'))
SUPPORTED_LANGUAGES = ['en', 'es', 'pt']
LANGUAGE_NAMES = {'en': 'English', 'es': 'Spanish', 'pt': 'Portuguese'}
BRAELO_MONGO_URI = os.getenv('BRAELO_MONGO_URI', os.getenv('BRAELO_MONGO_DB_URI', ''))  # optional: for sync_braelo_mongo
